image: registry.gitlab.com/joydenfew/python-ryu

# Defines stages which are to be executed
stages:  
  - build
  - deploy

# Stage "build"
run-build:  
  stage: build
  script:
    - apt-get update && apt-get upgrade -y
    - cd /builds/joydenfew/python-prometheus-client
    - echo "Installing packages required for package building"
    #- #apt-get install -y equivs devscripts dpkg-dev quilt curl nano apt-transport-https apt-utils ssl-cert ca-certificates gnupg lsb-release debhelper dh-systemd git
    - TAG="git describe --tags"
    #- #echo "deb https://packagecloud.io/faucetsdn/faucet/$(lsb_release -si | awk '{print tolower($0)}')/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/faucet.list && curl -L https://packagecloud.io/faucetsdn/faucet/gpgkey | apt-key add - && apt-get update
    - echo "installing build deps"
    - apt-get upgrade -y && mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
    - export DEBEMAIL='jfh13@students.waikato.ac.nz' && export DEBFULLNAME='Jayden Hewer'
    - debchange --newversion $($TAG) -b "Package automatically generated for new version of faucet"
    - fakeroot debian/rules binary
    - mkdir build
    - mv ../*.deb build/
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
  only:
      - tags

deploy-package:
  stage: deploy
  script:
    #- #apt-get update && apt-get install -y ruby-dev build-essential patch zlib1g-dev liblzma-dev make libffi-dev && gem update --system && gem install rake bundler rails json_pure sass compass package_cloud
    - cd /builds/joydenfew/python-prometheus-client/build
    #token is the cloud token set as a secret
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$TOKEN\"}" > ~/.packagecloud
    - package_cloud push Student/faucet/debian/jessie *.deb
    - package_cloud push Student/faucet/debian/stretch *.deb
    - package_cloud push Student/faucet/debian/buster *.deb
    - package_cloud push Student/faucet/ubuntu/xenial *.deb
    - package_cloud push Student/faucet/ubuntu/yakkety *.deb
    - package_cloud push Student/faucet/ubuntu/zesty *.deb
    - package_cloud push Student/faucet/ubuntu/artful *.deb
    - package_cloud push Student/faucet/ubuntu/bionic *.deb
  only:
      - tags

